import './globals.css' // Jika ada file CSS
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'ArduMaster Pro',
  description: 'Generated by Kang Mas',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black">{children}</body>
    </html>
  )
}